# Generated by Django 3.2.6 on 2021-08-04 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceAreas',
            new_name='ServiceArea',
        ),
    ]
