# Generated by Django 3.2.6 on 2021-08-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_rename_serviceareas_servicearea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
