# Generated by Django 3.2.6 on 2021-08-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_alter_servicearea_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicearea',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='servicearea',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
